SELECT TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_DEFAULT LIKE '(%)'
  AND TABLE_SCHEMA NOT IN ('mysql','information_schema','performance_schema','sys');
